[workspace]
members = [
    "ector",
    "macros",
]
resolver = "2"

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "cb9f0ef5b800ce4a22cde1805e0eb88425f1e07b" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "cb9f0ef5b800ce4a22cde1805e0eb88425f1e07b" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "cb9f0ef5b800ce4a22cde1805e0eb88425f1e07b" }
